package com.warehouse.mapper;

import com.warehouse.bean.WarehouseGoods;
import com.warehouse.bean.WarehouseGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WarehouseGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    long countByExample(WarehouseGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int deleteByExample(WarehouseGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int insert(WarehouseGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int insertSelective(WarehouseGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    List<WarehouseGoods> selectByExample(WarehouseGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    WarehouseGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") WarehouseGoods record, @Param("example") WarehouseGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int updateByExample(@Param("record") WarehouseGoods record, @Param("example") WarehouseGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int updateByPrimaryKeySelective(WarehouseGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    int updateByPrimaryKey(WarehouseGoods record);
}