package com.warehouse.bean;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.extends_parts
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String extendsParts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.created_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.updated_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.num
     *
     * @return the value of goods.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.num
     *
     * @param num the value for goods.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.extends_parts
     *
     * @return the value of goods.extends_parts
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getExtendsParts() {
        return extendsParts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.extends_parts
     *
     * @param extendsParts the value for goods.extends_parts
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setExtendsParts(String extendsParts) {
        this.extendsParts = extendsParts == null ? null : extendsParts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark
     *
     * @return the value of goods.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark
     *
     * @param remark the value for goods.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.operator
     *
     * @return the value of goods.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.operator
     *
     * @param operator the value for goods.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.created_at
     *
     * @return the value of goods.created_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.created_at
     *
     * @param createdAt the value for goods.created_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.updated_at
     *
     * @return the value of goods.updated_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.updated_at
     *
     * @param updatedAt the value for goods.updated_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}