package com.warehouse.bean;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator_name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operator_num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operatorNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.opreator_time
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date opreatorTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operation_type
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operation_detail
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operationDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operator_name
     *
     * @return the value of log.operator_name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operator_name
     *
     * @param operatorName the value for log.operator_name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operator_num
     *
     * @return the value of log.operator_num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperatorNum() {
        return operatorNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operator_num
     *
     * @param operatorNum the value for log.operator_num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperatorNum(String operatorNum) {
        this.operatorNum = operatorNum == null ? null : operatorNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.opreator_time
     *
     * @return the value of log.opreator_time
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getOpreatorTime() {
        return opreatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.opreator_time
     *
     * @param opreatorTime the value for log.opreator_time
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOpreatorTime(Date opreatorTime) {
        this.opreatorTime = opreatorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operation_type
     *
     * @return the value of log.operation_type
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operation_type
     *
     * @param operationType the value for log.operation_type
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operation_detail
     *
     * @return the value of log.operation_detail
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperationDetail() {
        return operationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operation_detail
     *
     * @param operationDetail the value for log.operation_detail
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperationDetail(String operationDetail) {
        this.operationDetail = operationDetail == null ? null : operationDetail.trim();
    }
}