package com.warehouse.bean;

import java.util.Date;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.receiver
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.receiver_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.responser
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String responser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.responser_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String responserPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.create_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.updatetime
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.num
     *
     * @return the value of supplier.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.num
     *
     * @param num the value for supplier.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.receiver
     *
     * @return the value of supplier.receiver
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.receiver
     *
     * @param receiver the value for supplier.receiver
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.receiver_phone
     *
     * @return the value of supplier.receiver_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.receiver_phone
     *
     * @param receiverPhone the value for supplier.receiver_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.responser
     *
     * @return the value of supplier.responser
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getResponser() {
        return responser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.responser
     *
     * @param responser the value for supplier.responser
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setResponser(String responser) {
        this.responser = responser == null ? null : responser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.responser_phone
     *
     * @return the value of supplier.responser_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getResponserPhone() {
        return responserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.responser_phone
     *
     * @param responserPhone the value for supplier.responser_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setResponserPhone(String responserPhone) {
        this.responserPhone = responserPhone == null ? null : responserPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.operator
     *
     * @return the value of supplier.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.operator
     *
     * @param operator the value for supplier.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.create_at
     *
     * @return the value of supplier.create_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.create_at
     *
     * @param createAt the value for supplier.create_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.updatetime
     *
     * @return the value of supplier.updatetime
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.updatetime
     *
     * @param updatetime the value for supplier.updatetime
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.remark
     *
     * @return the value of supplier.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.remark
     *
     * @param remark the value for supplier.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}