package com.warehouse.bean;

import java.util.ArrayList;
import java.util.List;

public class WarehouseGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public WarehouseGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGoodsNumIsNull() {
            addCriterion("goods_num is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumIsNotNull() {
            addCriterion("goods_num is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumEqualTo(String value) {
            addCriterion("goods_num =", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotEqualTo(String value) {
            addCriterion("goods_num <>", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumGreaterThan(String value) {
            addCriterion("goods_num >", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumGreaterThanOrEqualTo(String value) {
            addCriterion("goods_num >=", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumLessThan(String value) {
            addCriterion("goods_num <", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumLessThanOrEqualTo(String value) {
            addCriterion("goods_num <=", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumLike(String value) {
            addCriterion("goods_num like", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotLike(String value) {
            addCriterion("goods_num not like", value, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumIn(List<String> values) {
            addCriterion("goods_num in", values, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotIn(List<String> values) {
            addCriterion("goods_num not in", values, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumBetween(String value1, String value2) {
            addCriterion("goods_num between", value1, value2, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNumNotBetween(String value1, String value2) {
            addCriterion("goods_num not between", value1, value2, "goodsNum");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNameEqualTo(String value) {
            addCriterion("goods_name =", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThan(String value) {
            addCriterion("goods_name <", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameLike(String value) {
            addCriterion("goods_name like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotLike(String value) {
            addCriterion("goods_name not like", value, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameIn(List<String> values) {
            addCriterion("goods_name in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andGoodsNameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goodsName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumIsNull() {
            addCriterion("warehouse_num is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumIsNotNull() {
            addCriterion("warehouse_num is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumEqualTo(String value) {
            addCriterion("warehouse_num =", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumNotEqualTo(String value) {
            addCriterion("warehouse_num <>", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumGreaterThan(String value) {
            addCriterion("warehouse_num >", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumGreaterThanOrEqualTo(String value) {
            addCriterion("warehouse_num >=", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumLessThan(String value) {
            addCriterion("warehouse_num <", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumLessThanOrEqualTo(String value) {
            addCriterion("warehouse_num <=", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumLike(String value) {
            addCriterion("warehouse_num like", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumNotLike(String value) {
            addCriterion("warehouse_num not like", value, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumIn(List<String> values) {
            addCriterion("warehouse_num in", values, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumNotIn(List<String> values) {
            addCriterion("warehouse_num not in", values, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumBetween(String value1, String value2) {
            addCriterion("warehouse_num between", value1, value2, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNumNotBetween(String value1, String value2) {
            addCriterion("warehouse_num not between", value1, value2, "warehouseNum");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameIsNull() {
            addCriterion("warehouse_name is null");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameIsNotNull() {
            addCriterion("warehouse_name is not null");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameEqualTo(String value) {
            addCriterion("warehouse_name =", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotEqualTo(String value) {
            addCriterion("warehouse_name <>", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameGreaterThan(String value) {
            addCriterion("warehouse_name >", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameGreaterThanOrEqualTo(String value) {
            addCriterion("warehouse_name >=", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameLessThan(String value) {
            addCriterion("warehouse_name <", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameLessThanOrEqualTo(String value) {
            addCriterion("warehouse_name <=", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameLike(String value) {
            addCriterion("warehouse_name like", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotLike(String value) {
            addCriterion("warehouse_name not like", value, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameIn(List<String> values) {
            addCriterion("warehouse_name in", values, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotIn(List<String> values) {
            addCriterion("warehouse_name not in", values, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameBetween(String value1, String value2) {
            addCriterion("warehouse_name between", value1, value2, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andWarehouseNameNotBetween(String value1, String value2) {
            addCriterion("warehouse_name not between", value1, value2, "warehouseName");
            return (Criteria) this;
        }

        public Criteria andContainNumberIsNull() {
            addCriterion("contain_number is null");
            return (Criteria) this;
        }

        public Criteria andContainNumberIsNotNull() {
            addCriterion("contain_number is not null");
            return (Criteria) this;
        }

        public Criteria andContainNumberEqualTo(Long value) {
            addCriterion("contain_number =", value, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberNotEqualTo(Long value) {
            addCriterion("contain_number <>", value, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberGreaterThan(Long value) {
            addCriterion("contain_number >", value, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("contain_number >=", value, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberLessThan(Long value) {
            addCriterion("contain_number <", value, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberLessThanOrEqualTo(Long value) {
            addCriterion("contain_number <=", value, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberIn(List<Long> values) {
            addCriterion("contain_number in", values, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberNotIn(List<Long> values) {
            addCriterion("contain_number not in", values, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberBetween(Long value1, Long value2) {
            addCriterion("contain_number between", value1, value2, "containNumber");
            return (Criteria) this;
        }

        public Criteria andContainNumberNotBetween(Long value1, Long value2) {
            addCriterion("contain_number not between", value1, value2, "containNumber");
            return (Criteria) this;
        }

        public Criteria andBottommostIsNull() {
            addCriterion("bottommost is null");
            return (Criteria) this;
        }

        public Criteria andBottommostIsNotNull() {
            addCriterion("bottommost is not null");
            return (Criteria) this;
        }

        public Criteria andBottommostEqualTo(Long value) {
            addCriterion("bottommost =", value, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostNotEqualTo(Long value) {
            addCriterion("bottommost <>", value, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostGreaterThan(Long value) {
            addCriterion("bottommost >", value, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostGreaterThanOrEqualTo(Long value) {
            addCriterion("bottommost >=", value, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostLessThan(Long value) {
            addCriterion("bottommost <", value, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostLessThanOrEqualTo(Long value) {
            addCriterion("bottommost <=", value, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostIn(List<Long> values) {
            addCriterion("bottommost in", values, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostNotIn(List<Long> values) {
            addCriterion("bottommost not in", values, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostBetween(Long value1, Long value2) {
            addCriterion("bottommost between", value1, value2, "bottommost");
            return (Criteria) this;
        }

        public Criteria andBottommostNotBetween(Long value1, Long value2) {
            addCriterion("bottommost not between", value1, value2, "bottommost");
            return (Criteria) this;
        }

        public Criteria andTopmostIsNull() {
            addCriterion("topmost is null");
            return (Criteria) this;
        }

        public Criteria andTopmostIsNotNull() {
            addCriterion("topmost is not null");
            return (Criteria) this;
        }

        public Criteria andTopmostEqualTo(Long value) {
            addCriterion("topmost =", value, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostNotEqualTo(Long value) {
            addCriterion("topmost <>", value, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostGreaterThan(Long value) {
            addCriterion("topmost >", value, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostGreaterThanOrEqualTo(Long value) {
            addCriterion("topmost >=", value, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostLessThan(Long value) {
            addCriterion("topmost <", value, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostLessThanOrEqualTo(Long value) {
            addCriterion("topmost <=", value, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostIn(List<Long> values) {
            addCriterion("topmost in", values, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostNotIn(List<Long> values) {
            addCriterion("topmost not in", values, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostBetween(Long value1, Long value2) {
            addCriterion("topmost between", value1, value2, "topmost");
            return (Criteria) this;
        }

        public Criteria andTopmostNotBetween(Long value1, Long value2) {
            addCriterion("topmost not between", value1, value2, "topmost");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warehouse_goods
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 25 12:25:01 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table warehouse_goods
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}