package com.warehouse.bean;

public class WarehouseGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.id
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.goods_num
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private String goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.goods_name
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.warehouse_num
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private String warehouseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.warehouse_name
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private String warehouseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.contain_number
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private Long containNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.bottommost
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private Long bottommost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_goods.topmost
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    private Long topmost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.id
     *
     * @return the value of warehouse_goods.id
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.id
     *
     * @param id the value for warehouse_goods.id
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.goods_num
     *
     * @return the value of warehouse_goods.goods_num
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public String getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.goods_num
     *
     * @param goodsNum the value for warehouse_goods.goods_num
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setGoodsNum(String goodsNum) {
        this.goodsNum = goodsNum == null ? null : goodsNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.goods_name
     *
     * @return the value of warehouse_goods.goods_name
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.goods_name
     *
     * @param goodsName the value for warehouse_goods.goods_name
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.warehouse_num
     *
     * @return the value of warehouse_goods.warehouse_num
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public String getWarehouseNum() {
        return warehouseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.warehouse_num
     *
     * @param warehouseNum the value for warehouse_goods.warehouse_num
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setWarehouseNum(String warehouseNum) {
        this.warehouseNum = warehouseNum == null ? null : warehouseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.warehouse_name
     *
     * @return the value of warehouse_goods.warehouse_name
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public String getWarehouseName() {
        return warehouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.warehouse_name
     *
     * @param warehouseName the value for warehouse_goods.warehouse_name
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setWarehouseName(String warehouseName) {
        this.warehouseName = warehouseName == null ? null : warehouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.contain_number
     *
     * @return the value of warehouse_goods.contain_number
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public Long getContainNumber() {
        return containNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.contain_number
     *
     * @param containNumber the value for warehouse_goods.contain_number
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setContainNumber(Long containNumber) {
        this.containNumber = containNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.bottommost
     *
     * @return the value of warehouse_goods.bottommost
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public Long getBottommost() {
        return bottommost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.bottommost
     *
     * @param bottommost the value for warehouse_goods.bottommost
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setBottommost(Long bottommost) {
        this.bottommost = bottommost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_goods.topmost
     *
     * @return the value of warehouse_goods.topmost
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public Long getTopmost() {
        return topmost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_goods.topmost
     *
     * @param topmost the value for warehouse_goods.topmost
     *
     * @mbg.generated Wed Apr 25 17:07:20 CST 2018
     */
    public void setTopmost(Long topmost) {
        this.topmost = topmost;
    }

	@Override
	public String toString() {
		return "WarehouseGoods [goodsNum=" + goodsNum + ", goodsName=" + goodsName + ", warehouseNum=" + warehouseNum
				+ ", warehouseName=" + warehouseName + ", containNumber=" + containNumber + ", bottommost=" + bottommost
				+ ", topmost=" + topmost + "]";
	}
}