package com.warehouse.bean;

import java.util.Date;

public class Warehouse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.responser
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String responser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.responser_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String responserPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.company
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.contract_date
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date contractDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.updateed_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private Date updateedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.num
     *
     * @return the value of warehouse.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.num
     *
     * @param num the value for warehouse.num
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.name
     *
     * @return the value of warehouse.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.name
     *
     * @param name the value for warehouse.name
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.responser
     *
     * @return the value of warehouse.responser
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getResponser() {
        return responser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.responser
     *
     * @param responser the value for warehouse.responser
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setResponser(String responser) {
        this.responser = responser == null ? null : responser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.responser_phone
     *
     * @return the value of warehouse.responser_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getResponserPhone() {
        return responserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.responser_phone
     *
     * @param responserPhone the value for warehouse.responser_phone
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setResponserPhone(String responserPhone) {
        this.responserPhone = responserPhone == null ? null : responserPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.company
     *
     * @return the value of warehouse.company
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.company
     *
     * @param company the value for warehouse.company
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.contract_date
     *
     * @return the value of warehouse.contract_date
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getContractDate() {
        return contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.contract_date
     *
     * @param contractDate the value for warehouse.contract_date
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.operator
     *
     * @return the value of warehouse.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.operator
     *
     * @param operator the value for warehouse.operator
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.updateed_at
     *
     * @return the value of warehouse.updateed_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public Date getUpdateedAt() {
        return updateedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.updateed_at
     *
     * @param updateedAt the value for warehouse.updateed_at
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setUpdateedAt(Date updateedAt) {
        this.updateedAt = updateedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.remark
     *
     * @return the value of warehouse.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.remark
     *
     * @param remark the value for warehouse.remark
     *
     * @mbg.generated Wed Apr 25 12:25:01 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}